version: '3'

services:
  test:
    build: .

    volumes:
      - .:/app

    working_dir: /app

    command: sh -c "python3 -m pip install -r requirements.txt --user && python3 main.py"

    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    hostname: chrome
